project:
  type: book
  output-dir: docs
  
book:
  title: "MTH321, Section B"
  subtitle: "Spring 2025"
  
  navbar:
    title: "mth 321 :: Spring 25"
#    background: "#D0B8A8"
    search: true
    right:
      - href: glance.qmd
        text: At a Glance
  downloads: [pdf]
    
  sidebar:
    title: "wee title"
#    background: "#F8EDE3"
#   logo: "images/logo.png"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 2
  
  chapters:
    - index.qmd
    - support.qmd
    - glance.qmd
    - about.qmd
    - structure.qmd
    - grades.qmd
    - writing.qmd
    - UPElements.qmd
    
format:
  html:
    theme: [yeti, style/mth321.scss]
    toc: true
    link-external-icon: true
    link-external-newwindow: true

  pdf:
    documentclass: memoir
    margin-left: 30mm
    margin-right: 30mm
    toc: true
    number-sections: true
    colorlinks: true
    pdf-engine: pdflatex
    include-in-header:  
        - text: |
            \usepackage{enumitem}

    
editor: visual

