---
title: "Welcome!"
---

# Welcome! {.unnumbered}

Before we get into the details of the course, I want to share with you a few thoughts about my general approach to teaching and learning.  My main goal as the professor in this course is to help you succeed, not just in learning the material but in growing as a learner.  Learning takes effort, a willingness to try something that may not work, and an openness to learning from feedback.; my job is to create an environment in which all of you are supported in these aspects.

I am looking forward to getting to know each of you this semester and it is my sincere goal to make our time together (in class and out) productive and engaging.  I want you to feel comfortable coming to me with any questions or concerns that arise, mathematical and otherwise.   If you encounter any issues that interfere with your learning, whether they are physical, mental, emotional, economic, or otherwise, or if you experience discrimination or mistreatment of any sort, please contact me immediately.  Other resources for support include the Chair of the Math Department or the CAS Dean of Students.



```{r}
1 + 1
```

::: red
here is a thing

with a border

what else?
:::

\begin{tcolorbox}[colback=blue!7!white, before = \vspace{\baselineskip}]
\section{General Course Information}

is this included in the html output at all?  it seems not!
\end{tcolorbox}

```{css, echo = TRUE}
.red {
border: 3px solid blue;
border-color: red
}
```

## Another section!

check it out
